/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CardsTable: typeof import('./src/components/CardsTable.vue')['default']
    DeleteNoti: typeof import('./src/components/custom/DeleteNoti.vue')['default']
    DropDown: typeof import('./src/components/DropDown.vue')['default']
    EasyNotification: typeof import('./src/components/custom/EasyNotification.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDatePicker: typeof import('element-plus/es')['ElDatePicker']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    MenuBar: typeof import('./src/components/MenuBar.vue')['default']
    Notification: typeof import('./src/components/Notification.vue')['default']
    PageSelector: typeof import('./src/components/PageSelector.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SystemHeader: typeof import('./src/components/SystemHeader.vue')['default']
    UserSystemHeader: typeof import('./src/components/UserSystemHeader.vue')['default']
  }
}
